<div class="sidebar">
        <form method="post" action="#" id="search_form">
          <input class="search" type="text" name="search_field" placeholder="Cerca...">
        </form>
      </div>
      <div id="content">
        <!-- insert the page content here -->
        <h1>Benvenuto in TickeTo</h1>
        <p>In questo sito potrai acquistare biglietti per i tuoi eventi preferiti</p>
        <h2>Eventi che gestiamo:</h2>
        <ul><li>Concerti</li>
          <li>Partite</li>
          <li>Mostre</li>
          <li>Convegni</li>
          <li>Film</li>
        </ul></div>