<!DOCTYPE HTML>
<html><head><title>TickeTo</title><meta name="description" content="website description"><meta name="keywords" content="website keywords, website keywords"><meta http-equiv="content-type" content="text/html; charset=windows-1252"><link rel="stylesheet" type="text/css" href="css/style.css" title="style"></head><body>
  <div id="main">
    <div id="header">
      <div id="logo">
          <a href="index"></a>
      </div>
      <div id="menubar">
          <ul id="menu"><li class="selected"><a href="index">Home</a></li>
          <li><a href="Partner.html">Partner</a></li>
          <li><a href="Eventi.html">Catalogo Eventi</a></li>
          <li><a href="Contatti.html">Contattaci</a></li>
          <li><a href="Login.html">Login</a></li>
        </ul></div>
    </div>
    <div id="site_content">
      <div class="sidebar">
        <form method="post" action="#" id="search_form">
          <p>
            <input class="search" type="text" name="search_field" placeholder="Cerca..."><input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="css/search.png" alt="Search" title="Search"></p>
        </form>
      </div>
      <div id="content">
        <!-- insert the page content here -->
        <h1>Benvenuto in TickeTo</h1>
        <p>In questo sito potrai acquistare biglietti per i tuoi eventi preferiti</p>
        <h2>Eventi che gestiamo:</h2>
        <ul><li>Concerti</li>
          <li>Partite</li>
          <li>Mostre</li>
          <li>Convegni</li>
          <li>Film</li>
        </ul></div>
    </div>
    <div id="content_footer"></div>
    <div id="footer">
        © 2018 Ticketo.it 
</div>
  </div>
</body></html>
