<!DOCTYPE HTML>
<html>
    <link rel="stylesheet" type="text/css" href="css/style.css" title="style">
    <div id="site_content">
      <div class="sidebar">
        <form method="post" action="#" id="search_form">
          <p>
            <input class="search" type="text" name="search_field" placeholder="Cerca..."><input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="css/search.png" alt="Search" title="Search"></p>
        </form>
      </div>
      <div id="content">
        <!-- insert the page content here -->
        <h1>Benvenuto in TickeTo</h1>
        <p>In questo sito potrai acquistare biglietti per i tuoi eventi preferiti</p>
        <h2>Eventi che gestiamo:</h2>
        <ul><li>Concerti</li>
          <li>Partite</li>
          <li>Mostre</li>
          <li>Convegni</li>
          <li>Film</li>
        </ul></div>
    </div>
    <div id="content_footer"></div>
    <div id="footer">
        © 2018 Ticketo.it 
</div>
  </div>
</body></html>
