<h1>Benvenuto in TickeTo</h1>
<div class="sidebar">
      </div>
      <div id="content">
        <p>In questo sito potrai acquistare biglietti per i tuoi eventi preferiti</p>
        <h2>Eventi che gestiamo:</h2>
        <ul><?php foreach ($this->tipologie as $type) 
	  echo "<li> $type->tipologia </li>"?>
        </ul></div>
 <?php if($this->products instanceof Zend_Paginator) {
    echo $this->paginationControl($this->tipologia,'Sliding','public/_paginator.phtml');
}?>

