<h1>Benvenuto in TickeTo</h1>
<div class="sidebar">
    <div class="hand"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></div>
      </div>
      <div id="content">
        <p>In questo sito potrai acquistare biglietti per i tuoi eventi preferiti</p>
               <a class="ancora" target="_blank" href="../../../TWeb18-Gruppo4/docs/relazione-gruppo_04-2018.pdf">Documentazione Sito</a>
        <h2>Eventi che gestiamo:</h2>
        <ul><?php foreach ($this->tipologie as $type) 
	  echo "<li> $type->tipologia </li>"?>
        </ul></div>
 <?php if($this->products instanceof Zend_Paginator) {
    echo $this->paginationControl($this->tipologia,'Sliding','public/_paginator.phtml');
}?>

