<div class="sidebar">
    <br><br><br><h2>Non sei registrato?</h2>
    <a class="ancora" href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'registra',
                        ), 
                        'default',true
                    ); 
                 ?>" >Registrati qui</a>
</div>
<div class="form_settings">
    <h2>Login o registrati</h2>

    <?=$this->loginForm;?>
  
</div>