<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/AJAX.js'))
        ->appendFile($this->baseUrl('js/rowColor.js'))
	->captureStart() ?>
$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'public', 'action' => 'ajaxLogin',), 'default'); ?>';
	var formName='<?= $this->loginForm->getName() ?>';
	$(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>
<div class="sidebar">
    <br><br><br><h2>Non sei registrato?</h2>
    <a class="ancora" href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'registra',
                        ), 
                        'default',true
                    ); 
                 ?>" >Registrati qui</a>
</div>
<div class="form_settings">
    <h2>Login o registrati</h2>

    <?=$this->loginForm;?>
  
</div>