<div id="content">
    <h2>Catalogo Organizzatori</h2>
    <ul>
        <?php foreach ($this->Organizzazioni as $type){ 
          echo "<table class=elenco><th colspan=2>$type->nome</th>";
	  echo '<tr><td><img src="../../css/images/virginradio.png" width=100 height=></td>'; 
          echo "<td><p>$type->descrizione</p>"; 
          echo "<p>Missione: $type->missione"; 
          echo "<br>Recapito: $type->recapiti</p></td></tr></table>";
          echo '<hr>';
          
          

        }?>
    </ul>
</div>
<?php if($this->products instanceof Zend_Paginator) {
    echo $this->paginationControl($this->tipologia,'Sliding','public/_paginator.phtml');
}?>
