<h2>Catalogo Organizzatori</h2>

        <?php foreach ($this->Organizzazioni as $type){ 
          echo "<div class=tabella><table class=elenco><th colspan=2>$type->nome</th>";
	  echo "<tr><td>";
          echo $this->img($type->immagine);
          echo "</td>"; 
          echo "<td><p>$type->descrizione</p>";
          echo "Missione: $type->missione";
          echo "<br>Recapito: $type->recapiti</td></tr></table></div>";}
          ?>

<?php if($this->products instanceof Zend_Paginator) {
    echo $this->paginationControl($this->tipologia,'Sliding','public/_paginator.phtml');
}