<h2>Catalogo Eventi</h2>
<?php
$filename='toggleEventi.js';
echo $this->toggleEventi($filename);
$id=0; $numeroacquisti=0;
?>

<div class="sidebar">
                <div class="ricerca">
                     <?php echo $this->ricercaForm ?>
                    </div>
    </div>

    
        <?php
          if(count($this->Eventi)==0)
          {echo'<h3>Non ci sono eventi che corrispondono alla tua ricerca</h3>';}
          foreach ($this->Eventi as $type){
          $biglietti=$type->numerobiglietti-$this->Biglietti;
          echo "<div class=tabella><table class=elenco><th colspan=2>$type->nome</th>";
	  echo "<tr><td>";
          echo $this->img($type->immagine); ?>
          <?php if($this->ruolo == 'user') :?>
          <form id="acquista" method="post">
          <div class="form_settings">
              Numero biglietti<br>
              <select class="numerobiglietti"><option>1</option><option>2</option><option>3</option><option>4</option>
              <option>5</option><option>6</option><option>7</option><option>8</option></select>
              <br>Metodo di pagamento
              <select class="pagamento"><option>Paypal</option><option>Bonifico Bancario</option><option>VISA</option>
              <option>MasterCard</option></select>
          <input class="submit" type="submit" name="contact_submitted" value="Acquista" href="
                        <?=$this->url(array(
                        'controller' => 'user',
                        'action'     => 'acquisto',
                        ), 
                        'default',true
                    )?>
          "></div></form><?php endif?>
          <?php
          echo "</td>"; 
          echo "<td><p>$type->descrizione</p>";
          echo "Prezzo: $type->prezzo";
          echo "<br>Luogo: $type->luogo"; 
          echo "<br>Data: $type->data";
          echo "<br>Orario di inizio: $type->orario</p>";
          echo '<br><a onclick='."toggleEventi($id)".'>Clicca qui per saperne di più</a></td></tr></table></div>';
          echo '<div class='."estensione".' id='."$id".'>';
          echo "<div class=tabella><table class=elenco><tr colspan=2>";
          echo "<td>Programma:<p>$type->programma</p>";
          echo "Biglietti rimanenti: $biglietti<br>";
          echo "Evento organizzato da $type->organizzatore";
          //echo "<br><b>$type->partecipazioni sono interessate a partecipare</b>"; qua va fatta la query che calcola quanti partecipazioni sono collegate all'evento
          echo "<iframe src=$type->mappa width='400px' height='240px'></iframe>";
          echo "</td></tr></table></div></div>";
          $id++;
        }
          ?>

<?php if($this->Eventi instanceof Zend_Paginator) {
    echo $this->paginationControl($this->Eventi,'Sliding','public/_paginator.phtml');
}