<h2>Chi siamo?</h2>
<p>Siamo un'azienda che vende biglietti per eventi di ogni tipo.<br>
   Se vuoi conoscerci meglio, lavorare con noi o chiedere qualsiasi altra informazione clicca sul pulsante Contattaci
   qui sotto e scrivici un'e-mail.</p>
<form action="mailto:info@TicketTo.it" method="post" >
    <div class="form_settings">
    <input class="submit" type="submit" name="contact_submitted" value="Contattaci">
    </div>
        </form>