<?php
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
?>
<div class="form_settings">
 <h3>Analisi vendite</h3>
</div>
        <?php echo "<div class=tabella id=gestione><table class=elenco><th>Immagine</th><th>Evento</th><th>Biglietti venduti</th><th>Percentuale biglietti venduti</th><th>Incasso</th>";
          foreach ($this->Eventi as $type):
          if($type->organizzatore==$this->Nome):
          
          $A=0;  
          foreach ($this->Acquisti as $t){if($t->nomeevento===$type->nome){$A=$A+$t->numerobiglietti;}}
          $P=($A*100)/($type->numerobiglietti);
              
	  echo "<tr><td>";
          echo $this->img($type->immagine);
          echo "</td><td>$type->nome</td>";
          echo "<td>$A</td><td>$P %</td>";
          $I=$type->prezzo*$A;
          echo "<td>$I €</td></tr>";
          
          endif; endforeach;
          echo '</table></div>';
          
