<?php
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
echo '<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">';
echo  '<link rel="stylesheet" href="/resources/demos/style.css">';
echo '<script src="https://code.jquery.com/jquery-1.12.4.js"></script>';
echo '<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
$filename='dp.js';
echo $this->jS($filename);
?>
<div class="form_settings">
 <h3>Analisi vendite</h3>
</div>
        <?php echo "<div class=tabella id=gestione><table class=elenco><th>Immagine</th><th>Evento</th><th>Biglietti venduti</th><th>Percentuale biglietti venduti</th><th>Incasso</th><th>Parteciperò</th>";
          foreach ($this->Eventi as $type):
          if($type->organizzatore==$this->Nome):
          
          $A=0;$sconto=0;$sco=0;  
          foreach ($this->Acquisti as $t){
              if($t->nomeevento===$type->nome){
                  $A=$A+$t->numerobiglietti;
                  if($t->sconto !=0 ){$sconto=$t->sconto;}
              }}
          $P=($A*100)/($type->numerobiglietti);
              
	  echo "<tr><td>";
          echo $this->img($type->immagine);
          echo "</td><td>$type->nome</td>";
          echo "<td>$A</td><td>$P %</td>";
          if($sconto != 0){$sco=(($type->prezzo*$sconto)/100);$I=(($type->prezzo-$sco)*$A);}
          else {$I=$type->prezzo*$A;}
          echo "<td>$I €</td><td>";
          
          foreach ($this->Part as $part){
              if($part->nomeevento===$type->nome){
                  foreach ($this->Utenti as $ut){
                      if($part->username===$ut->username){echo "$ut->nome&nbsp$ut->cognome<br>";}
                  }
              }
          }
          echo '</td><tr>';
          endif; endforeach;
          echo '</table></div>';
          ?>
          <h3>Seleziona un periodo di cui vuoi sapere l'incasso totale</h3>
          <?php echo $this->dataForm; 