<div class="form_settings">
 <h3>Gestisci eventi</h3>
 <p>Utilizza questa sezione per gestire gli eventi nel Catalogo</p>
</div>
        <?php foreach ($this->Eventi as $type){
          if($type->organizzatore==$this->Nome){
          echo "<div class=tabella><table class=elenco><th colspan=2>$type->nome</th>";
	  echo "<tr><td>";
          echo $this->img($type->immagine);
          echo '</td><td><input class="submit" type="submit" value="MODIFICA">';
          echo '<input class="submit" type="submit" value="ELIMINA"></td></tr></table></div>';
          }
        }
          ?>

<?php if($this->Eventi instanceof Zend_Paginator) {
    if($type->organizzatore==$this->Nome){
    echo $this->paginationControl($this->Eventi,'Sliding','partner/_paginator.phtml');}
}