<?php
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
?>
<div class="form_settings">
 <h3>Gestisci eventi</h3>
 <p>Utilizza questa sezione per gestire gli eventi nel Catalogo</p>
</div>
        <?php foreach ($this->Eventi as $type):
           if($type->organizzatore==$this->Nome):
          echo "<div class=tabella><table class=elenco><th colspan=2>$type->nome</th>";
	  echo "<tr><td>";
          echo $this->img($type->immagine);
          echo "</td><td>";
           ?>
        <a  class="ancora" type="submit" onclick="return conferma()" href="<?= $this->url(array(
                        'controller' => 'partner',
                        'action'     => 'elimina',
                        'id_E'       => $type->id_E,
                        'nome'       => $type->nome,
                        ), 
                        'default',true
         );?>">Elimina</a><br><br>
          <a  class="ancora" type="submit" href="<?= $this->url(array(
                        'controller' => 'partner',
                        'action'     => 'modev',
                        'id_E'       => $type->id_E,
                        ), 
                        'default',true
         );?>">Modifica</a>
          <?php echo '</td></tr>' ?>
          <?php endif; endforeach;
          echo '</table></div>'?>

         
    <?php if($this->Eventi instanceof Zend_Paginator) {
    if($type->organizzatore==$this->Nome){
    echo $this->paginationControl($this->Eventi,'Sliding','partner/_paginator.phtml');
    }
    }