<!--<script>
function cancella() {
  var domanda = confirm("Sei sicuro di voler cancellare?");
  if (domanda === true) {
    alert('Qui metti un redirect alla URL che effettua la cancellazione...')  
  }else{
    alert('Operazione annullata');
  }
}
}</script>-->

<div class="form_settings">
 <h3>Gestisci eventi</h3>
 <p>Utilizza questa sezione per gestire gli eventi nel Catalogo</p>
</div>
        <?php foreach ($this->Eventi as $type){
          if($type->organizzatore==$this->Nome){
          echo "<div class=tabella><table class=elenco><th colspan=2>$type->nome</th>";
	  echo "<tr><td>";
          echo $this->img($type->immagine);
          echo '</td><td>';
          //echo $this->gestisciForm;//
          echo '<form  method="post" href="'.$this->url(array(
                        'controller' => 'partner',
                        'action'     => 'elimina',
                        ), 
                        'default',true
                    ).'"><input class="submit" type="submit" value="Elimina"></form>';
          echo '</td></tr></table></div>';
          }
        }
          ?>

<?php if($this->Eventi instanceof Zend_Paginator) {
    if($type->organizzatore==$this->Nome){
    echo $this->paginationControl($this->Eventi,'Sliding','partner/_paginator.phtml');}
}