<?php
echo '<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">';
echo  '<link rel="stylesheet" href="/resources/demos/style.css">';
echo '<script src="https://code.jquery.com/jquery-1.12.4.js"></script>';
echo '<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
$filename='dp.js';
echo $this->jS($filename);
?>
<div class="static">
 <h3>Modifica Evento</h3>
 <p>Utilizza questa form per modificare una evento esistente</p>
  <?php echo $this->modevForm ?>
</div>