<?php
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
?>
<div class="static">
 <h3>Modifica Evento</h3>
 <p>Utilizza questa form per modificare una evento esistente</p>
  <?php echo $this->modevForm ?>
</div>