<?php
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
?>
<div class="form_settings">
 <h3>Aggiungi Evento</h3>
 <p>Utilizza questa form per inserire un nuovo evento nel Catalogo</p>
  <?php echo $this->addForm ?>
</div>