<ul id="menu">
          <li class="selected"><a href="
                         <?= $this->url(array(
                        'controller' => 'index',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>" >Home</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'index',
                        'action'     => 'viewstatic',
                        'staticPage' => 'partner', 
                        ), 
                        'default',true
                    ); 
                 ?>" >Catalogo</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'index',
                        'action'     => 'viewstatic',
                        'staticPage' => 'catalogo', 
                        ), 
                        'default',true
                    ); 
                 ?>" >Contattaci</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'index',
                        'action'     => 'viewstatic',
                        'staticPage' => 'contattaci', 
                        ), 
                        'default',true
                    ); 
                 ?>" >Login</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'index',
                        'action'     => 'viewstatic',
                        'staticPage' => 'login', 
                        ), 
                        'default',true
                    ); 
                 ?>" >Partner</a>
              </li>
</ul>