<ul id="menu">
          <li><a href="
                         <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>" >Home</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => ''
                        ), 
                        'default',true
                    ); 
                 ?>" >Utenti</a>
                     </li>
                          <li><a href="
                         <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => ''
                        ), 
                        'default',true
                    ); 
                 ?>" >Organizzatori</a>
                          </li>
                           <li><a href="
                         <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => ''
                        ), 
                        'default',true
                    ); 
                 ?>" >Tipologie Eventi</a>
                          </li>
                    <li><a href="
                         <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => ''
                        ), 
                        'default',true
                    ); 
                 ?>" >Gestione FAQ</a>
                          </li>
                    <li><a href="
                         <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'logout'
                        ), 
                        'default',true
                    ); 
                 ?>" >Logout</a>
              </li>
</ul>