<ul id="menu">
          <li><a href="
                         <?= $this->url(array(
                        'controller' => 'partner',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>" >Home</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'partner',
                        'action'     => 'newproduct'
                        ), 
                        'default',true
                    ); 
                 ?>" >Aggiungi Evento</a>
              </li>
                    <li><a href="
                         <?= $this->url(array(
                        'controller' => 'partner',
                        'action'     => '', 
                        ), 
                        'default',true
                    ); 
                 ?>" >Modifica</a>
              </li>
              <li><a href="
                         <?= $this->url(array(
                        'controller' => 'partner',
                        'action'     => '', 
                        ), 
                        'default',true
                    ); 
                 ?>" >Cancella</a>
              </li>
              <li><a href="
                         <?= $this->url(array(
                        'controller' => 'partner',
                        'action'     => '', 
                        ), 
                        'default',true
                    ); 
                 ?>" >Analisi Vendite</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'logout'
                        ), 
                        'default',true
                    ); 
                 ?>" >Logout</a>
              </li>
</ul>