<ul id="menu">
          <li class="selected"><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>" >Home</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'eventi'
                        ), 
                        'default',true
                    ); 
                 ?>" >Catalogo</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'organizzazioni'
                        ), 
                        'default',true
                    ); 
                 ?>" >Partner</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'where', 
                        ), 
                        'default',true
                    ); 
                 ?>" >Dove Siamo</a>
              </li>
               <li><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' => 'who', 
                        ), 
                        'default',true
                    ); 
                 ?>" >Chi siamo</a>
              </li>
                             <li><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'faq', 
                        ), 
                        'default',true
                    ); 
                 ?>" >FAQ</a>
              </li>
                     <li><a href="
                         <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login',
                        ), 
                        'default',true
                    ); 
                 ?>" >Login</a>
              </li>
</ul>