<?php echo $this->doctype() ?>
<html>
<head>
    <?= $this->headTitle(); ?>
    <meta name="description" content="website description">
    <meta name="keywords" content="website keywords, website keywords">
    <meta http-equiv="content-type" content="text/html; charset=windows-1252">
    <?= $this->headLink(); ?>
</head>
<body>
  <div id="main">
    <div id="header">
      <div id="logo">
      </div>
      <div id="menubar">
          <?= $this->render('_menubar.phtml') ?>
      </div>
    </div>
        <div id="site_content">
            <div class="sidebar">
                <ul>
                    <li><a class="" href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'gestisciutente',
                        ), 
                        'default',true
                    ); 
                    ?>">Gestisci utenti</a></li>
                    <li><a class="" href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'newpartner',
                        ), 
                        'default',true
                    ); 
                    ?>">Aggiungi nuovo organizzatore</a></li>
                    <li><a class="" href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'newtipev',
                        ), 
                        'default',true
                    ); 
                    ?>">Aggiungi nuova tipologia evento</a></li>
                    <li><a class="" href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'gestiscitipev',
                        ), 
                        'default',true
                    ); 
                    ?>">Gestisci tipologia evento</a></li>
                    <li><a>Acquisti degli utenti</a></li>
                    <li><a class="" href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'newfaq',
                        ), 
                        'default',true
                    ); 
                    ?>">Aggiungi nuova FAQ</a></li>
                    <li><a class="" href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'gestiscifaq',
                        ), 
                        'default',true
                    ); 
                    ?>">Gestisci FAQ</a></li>
                </ul>
      </div>
            <?php echo $this->layout()->content; ?>
        </div>
  </div>
    <footer id="footer">
        <p>© 2018 Ticketo.it</p>
    </footer>
</html>

