<?php echo $this->doctype() ?>
<html>
<head>
    <?= $this->headTitle(); ?>
    <meta name="description" content="website description">
    <meta name="keywords" content="website keywords, website keywords">
    <meta http-equiv="content-type" content="text/html; charset=windows-1252">
    <?= $this->headLink(); ?>
    <?= $this->headScript(); ?>
</head>
<body>
  <div id="main">
    <div id="header">
      <div id="logo">
      </div>
      <div id="menubar">
          <?= $this->render('_menubar.phtml') ?>
      </div>
    </div>
        <div id="site_content">
            <?php echo $this->layout()->content; ?>
        </div>
  </div>
    <footer id="footer">
        <p>© 2018 Ticketo.it - <a target="_blank" href="../../../TWeb18-Gruppo4/docs/relazione-gruppo_04-2018.pdf">Link Relazione in PDF</a></p>
    </footer>
</html>

