<?php echo $this->doctype() ?>
<html>
<head>
    <?= $this->headTitle(); ?>
    <meta name="description" content="website description">
    <meta name="keywords" content="website keywords, website keywords">
    <meta http-equiv="content-type" content="text/html; charset=windows-1252">
    <?= $this->headLink(); ?>
</head>
<body>
  <div id="main">
    <div id="header">
      <div id="logo">
      </div>
      <div id="menubar">
          <?= $this->render('_menubar.phtml') ?>
      </div>
    </div>
  </div>

 <div id="footer">
	<br>
	<p>TicketTo</p>
</div>
</body>
</html>

