<head><title>TickeTo</title><meta name="description" content="website description"><meta name="keywords" content="website keywords, website keywords"><meta http-equiv="content-type" content="text/html; charset=windows-1252"><link rel="stylesheet" type="text/css" href="css/style.css" title="style"></head><body>
  <div id="main">
    <div id="header">
      <div id="logo">
      </div>
      <div id="menubar">
          <ul id="menu"><li class="selected"><a href="
                         <?= $this->url(array(
                        'controller' => 'index',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>" >Home</a></li>
          <li><a href="Partner.html">Partner</a></li>
          <li><a href="Eventi.html">Catalogo Eventi</a></li>
          <li><a href="Contatti.html">Contattaci</a></li>
          <li><a href="Login.html">Login</a></li>
        </ul></div>
    </div>

