<?php
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
?>
<h2>I miei acquisti</h2>
<?php   echo "<div class=tabella id=gestione><table class=elenco><th>Evento</th><th>Biglietti acquistati</th><th>Metodo di pagamento</th><th>Ricevuta di acquisto</th>";
        foreach ($this->acquisti as $type):
        if($this->utente===$type->username):
        echo "<tr><td>$type->nomeevento</td>";
        echo "<td>$type->numerobiglietti</td><td>";?>
        <?php if($type->metodo==='V'){echo 'Visa';}
              if($type->metodo==='M'){echo 'Mastercard';}
              if($type->metodo==='B'){echo 'Bonifico bancario';}
        
        echo '</td><td>';?>
        <a  class="ancora" type="submit" href="<?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'genpdf',
                        'nomeevento'=> $type->nomeevento,
                        'numerobiglietti'=>$type->numerobiglietti,
                        'metodo'=>$type->metodo,
                        'titolo'=>'Biglietto '.$type->nomeevento), 
                        'default',true
         );?>">Stampa</a>
        <?php
        endif;
        endforeach;
        echo '</tr></table></div>';