<?php
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
?>
<h3>Inserisci i dati per procedere con l'acquisto </h3>
<ul class="form_settings">
    
<?php echo $this->acquistoForm; echo $this->nomeevento;