<h2>Catalogo Eventi</h2>
<?php
$filename='toggleEventi.js';
echo $this->jS($filename);
$id=0; $numeroacquisti=0;
?>

<div class="sidebar">
                <div class="ricerca">
                     <?php echo $this->ricercaForm ?>
                    </div>
    </div>

    
        <?php foreach ($this->Eventi as $type){
          $biglietti=$type->numerobiglietti-$this->Biglietti;
          echo "<div class=tabella><table class=elenco><th colspan=2>$type->nome</th>";
	  echo "<tr><td>";
          echo $this->img($type->immagine); ?><br><br><br>
          
          <?php if($type->numerobiglietti != 0):?><a  class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'confermaacq',
                        'nomeevento' => $type->nome), 
                        'default',true
        );?>" >Acquista </a><br><br><?php endif;?>
        <?php if($type->numerobiglietti == 0):?><a  class="ancora" type="submit">Biglietti terminati </a><br><br><?php endif;?>
        <?php if($type->numerobiglietti != 0):?>
        <?php $bool=false; foreach ($this->Part as $part){if($part->username===$this->Username and $part->nomeevento===$type->nome){$bool=true;}}
        if($bool===false):?>
        <a  class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'partecipazione',
                        'nomeevento' => $type->nome), 
                        'default',true
                    );?>" >Parteciperò</a>
          <?php endif;
          if($bool===true):?> <a class="ancora" type="submit" onclick="alert('Hai già espresso la tua intenzione a partecipare a questo evento!')"> Parteciperò</a>
          <?php endif;endif;
          echo "</td>"; 
          echo "<td><p>$type->descrizione</p>";
          echo "Prezzo: $type->prezzo €";
          echo "<br>Luogo: $type->luogo"; 
          echo "<br>Data: $type->data";
          echo "<br>Orario di inizio: $type->orario";
          $partecipazioni=0;
          foreach ($this->Part as $part){if($part->nomeevento===$type->nome){$partecipazioni=($partecipazioni+1);}}
          echo "<br><b>$partecipazioni persone sono interessate a partecipare</b></p>";
          echo '<br><a class=ancora onclick='."toggleEventi($id)".'>Clicca qui per saperne di più</a></td></tr></table></div>';
          echo '<div class='."estensione".' id='."$id".'>';
          echo "<div class=tabella><table class=elenco><tr colspan=2>";
          echo "<td>Programma:<p>$type->programma</p>";
          echo "Biglietti rimanenti: $biglietti<br>";
          echo "Evento organizzato da $type->organizzatore";
          if($type->mappa != null):?> <iframe src=<?= $type->mappa?> width='400px' height='240px' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>
          <?php endif;
          echo "</td></tr></table></div></div>";
          $id++;
        }
          ?>

<?php if($this->Eventi instanceof Zend_Paginator) {
    echo $this->paginationControl($this->Eventi,'Sliding','user/_paginator.phtml');
}
