<h2>Catalogo Eventi</h2>
<?php
echo '<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">';
echo  '<link rel="stylesheet" href="/resources/demos/style.css">';
echo '<script src="https://code.jquery.com/jquery-1.12.4.js"></script>';
echo '<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>';
$filename='toggleEventi.js';
echo $this->jS($filename);
$filename='dp.js';
echo $this->jS($filename);
$id=0; $numeroacquisti=0;
?>

<div class="sidebar">
                <div class="ricerca">
                     <?php echo $this->ricercaForm ?>
                    </div>
    </div>

    
        <?php
          if(count($this->Eventi)==0)
          {echo'<h3>Non ci sono eventi che corrispondono alla tua ricerca</h3>';}
          foreach ($this->Eventi as $type){
          $biglietti=$type->numerobiglietti-$this->Biglietti;
          echo "<div class=tabella><table class=elenco><th colspan=2>$type->nome</th>";
	  echo "<tr><td>";
          echo $this->img($type->immagine); ?>
          <br><br><br><a  class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'confermaacq',
                        'nomeevento' => $type->nome), 
                        'default',true
                  );?>" >Acquista </a><br><br>
        <?php $bool=false; foreach ($this->Part as $part){if($part->username===$this->Username and $part->nomeevento===$type->nome){$bool=true;}}
        if($bool===false):?>
        <a  class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'user',
                        'action'     => 'partecipazione',
                        'nomeevento' => $type->nome), 
                        'default',true
                    );?>" >Parteciperò</a>
          <?php endif;
          if($bool===true):?> <a class="ancora" type="submit" onclick="alert('Hai già espresso la tua intenzione a partecipare a questo evento!')"> Parteciperò</a>
          <?php endif;
          echo "</td>"; 
          echo "<td><p>$type->descrizione</p>";
          echo $this->price($type);
          echo "<br>Luogo: $type->luogo"; 
          echo "<br>Data: $type->data";
          echo "<br>Orario di inizio: $type->orario";
          $partecipazioni=0;
          foreach ($this->Part as $part){if($part->nomeevento===$type->nome){$partecipazioni=($partecipazioni+1);}}
          echo "<br><b>$partecipazioni persone sono interessate a partecipare</b></p>";
          echo '<br><a class=ancora onclick='."toggleEventi($id)".'>Clicca qui per saperne di più</a></td></tr></table></div>';
          echo '<div class='."estensione".' id='."$id".'>';
          echo "<div class=tabella><table class=elenco><tr colspan=2>";
          echo "<td>Programma:<p>$type->programma</p>";
          echo "Biglietti rimanenti: $biglietti<br>";
          echo "Evento organizzato da $type->organizzatore";
          //echo "<br><b>$type->partecipazioni sono interessate a partecipare</b>"; qua va fatta la query che calcola quanti partecipazioni sono collegate all'evento
          if($type->mappa != null):?> <iframe src= <?= $type->mappa ?> width='400px' height='240px' frameborder='0' scrolling='no' marginheight='0' marginwidth='0'></iframe>
          <?php endif;
          echo "</td></tr></table></div></div>";
          $id++;
        }
