<?php
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
?>
<div>
 <h3>Gestisci Organizzatori</h3>
 <p>Utilizza questa form per gestire i dati degli organizzatori</p>
</div>
<div class=tabella id=gestione><table class=elenco><th>Username</th><th>Nome</th>
            <?php foreach ($this->utenti as $type):
            if($type->ruolo==='partner'):
            echo "<tr><td>$type->username</td>";
            echo "<td>$type->nome</td>";
            echo "<td>";?>
            <a  class="ancora" type="submit" onClick=" return conferma()"  href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'eliminapart',
                        'id_U'       => $type->id_U,
                        'nome'       => $type->nome,
                        ), 
                        'default',true
                    );?>" value="Elimina">Elimina</a>
             </td><td><a  class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'modpart',
                        'username'   => $type->username,
                        'nome'       => $type->nome,
                        'id_U'       => $type->id_U,
                        ), 
                        'default',true
                    );?>" value="Modifica">Modifica</a></td>
            <?php echo '</tr>';
            endif; endforeach;
            echo '</table></div>';