<div>
 <h3>Gestisci FAQ</h3>
 <p>Utilizza questa form per gestire le FAQ</p>
</div>
<div class=tabella id=gestione><table class=elenco><th>Tipologia</th>
            <?php foreach ($this->tipoeventi as $type):
            echo "<tr><td>$type->tipologia</td><td>";
            ?>
             <a  class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'eliminatipev',
                        'id_TE'       => $type->id_TE), 
                        'default',true
                    );?>" value="Elimina">Elimina</a>
            <?php echo '</td><td><input class"submit" type="submit" value="Modifica"></td></tr>';?>
            <?php endforeach;
            echo '</table></div>'?>