<?php
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
?>
<div>
 <h3>Gestisci FAQ</h3>
 <p>Utilizza questa form per gestire le FAQ</p>
 
<?php if($this->elimina):?>
<?php echo '<h5 style="color:red">FAQ eliminata</h4>'?>
<?php endif ?>
<?php if($this->modifica):?>
<?php echo '<h5 style="color:red">FAQ modificata</h4>'?>
<?php endif ?>
 
</div>
<?php       
            foreach ($this->faq as $type):
            echo "<p><li> $type->domanda</li>"; 
            echo "<br>$type->risposta<br></p>";?>
            <td><a class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'modfaq',
                        'id_F'       => $type->id_F), 
                        'default',true
                    );?>" >Modifica</a></td>
            
            
            
            
            <td><a  class="ancora" onclick="return conferma()" type="submit" href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'eliminafaq',
                        'id_F'       => $type->id_F), 
                        'default',true
                    );?>" value="Elimina">Elimina</a></td></tr><br><br><hr>
             <?php endforeach?>