<?php
$filename='conferma.js';
echo $this->toggleEventi($filename);?><div>
 <h3>Gestisci FAQ</h3>
 <p>Utilizza questa form per gestire le FAQ</p>
</div>
<?php       
            foreach ($this->faq as $type):
            echo "<p><li> $type->domanda</li>"; 
            echo "<br>$type->risposta<br></p>";?>
            <td><a class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'modfaq',
                        'id_F'       => $type->id_F), 
                        'default',true
                    );?>" >Modifica</a></td>
            
            
            
            
            <td><a  class="ancora" onclick="return conferma()" type="submit" href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'eliminafaq',
                        'id_F'       => $type->id_F), 
                        'default',true
                    );?>" value="Elimina">Elimina</a></td></tr><br><br><hr>
             <?php endforeach?>