<?php
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
?>
<div>
 <h3>Gestisci utenti</h3>
 <p>Utilizza questa form per gestire i dati degli utenti</p>
 
<?php if($this->elimina):?>
<?php echo '<h5 style="color:red">Utente '.$this->user.' eliminato</h4>'?>
<?php endif ?>
<?php if($this->modifica):?>
<?php echo '<h5 style="color:red">Utente '.$this->user.' modificato.</h4>'?>
<?php endif ?>

</div>
<div class=tabella id=gestione><table class=elenco><th>Username</th><th>Nome</th><th>Cognome</th>
            <?php foreach ($this->utenti as $type):
            if($type->ruolo!='admin' && $type->ruolo!='partner'):
            echo "<tr><td>$type->username</td>";
            echo "<td>$type->nome</td>";
            echo "<td>$type->cognome</td><td>";?>
            <a  class="ancora" type="submit" onClick=" return conferma()"  href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'elimina',
                        'id_U'       => $type->id_U,
                        'nome'       => $type->nome,
                        ), 
                        'default',true
                    );?>" value="Elimina">Elimina</a>
             </td><td><a  class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'moduser',
                        'username'   => $type->username,
                        ), 
                        'default',true
                    );?>" value="Modifica">Modifica</a>
             </td><?php if($type->ruolo==='user'):?>
             <td><a  class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'profacqui',
                        'username'   => $type->username,
                        'nome'       => $type->nome,
                        'cognome'    => $type->cognome
                        ), 
                        'default',true
                    );?>" value="Modifica">Profilo di acquisto</a></td>
            <?php endif;echo '</tr>' ?>
            <?php endif; endforeach;
            echo '</table></div>'?>
