<?php
$filename='toggleEventi.js';
echo $this->toggleEventi($filename);
$id=0;?>
<div>
 <h3>Gestisci utenti</h3>
 <p>Utilizza questa form per gestire i dati degli utenti</p>
</div>
<div class=tabella id=gestione><table class=elenco><th>Username</th><th>Ruolo</th><th>Nome</th><th>Cognome</th>
            <?php foreach ($this->utenti as $type):
            if($type->ruolo!='admin'):
            echo "<tr><td>$type->username</td>";
            echo "<td>$type->ruolo</td>";
            echo "<td>$type->nome</td>";
            echo "<td>$type->cognome</td><td>";?>
            <a  class="ancora" type="submit" href=" <?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'elimina',
                        'id_U'       => $type->id_U,
                        'nome'       => $type->nome,
                        ), 
                        'default',true
                    );?>" value="Elimina">Elimina</a>
            <?php echo '</td><td><input class"submit" type="submit" value="Modifica"></td></tr>';?>
            <?php endif; endforeach;
            echo '</table></div>'?>