<?php
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
?>
<div class="static">
 <h3>Aggiungi Tipologia evento</h3>
 <p>Utilizza questa form per inserire una nuova tipologia di eventi</p>
  <?php echo $this->addtipevForm ?>
</div>