<h3>Profilo acquisto di <?php echo "$this->nome $this->cognome" ?></h3>
<div class=tabella id=gestione><table class=elenco><th>Eventi</th><th>Biglietti acquistati</th><th>Metodo di pagamento</th><th>Totale speso</th>
<?php foreach ($this->acq as $type):
    if($type->username===$this->username):
    echo "<tr><td>$type->nomeevento</td>";
    echo "<td>$type->numerobiglietti</td><td>";?>
        <?php if($type->metodo==='V'){echo 'Visa';}
              if($type->metodo==='M'){echo 'Mastercard';}
              if($type->metodo==='B'){echo 'Bonifico bancario';}
    $tot=0;
    foreach ($this->pr as $t){if($t->nome===$type->nomeevento){$tot=($t->prezzo*$type->numerobiglietti);}}
    echo "</td><td>$tot</td></tr>";
        
    
endif; endforeach;?>
    </table></div>
