<h3>Profilo acquisto di <?php echo "$this->nome $this->cognome" ?></h3>
<div class=tabella id=gestione><table class=elenco><th>Eventi</th><th>Biglietti acquistati</th><th>Metodo di pagamento</th>
<?php foreach ($this->acq as $type):
    if($type->username===$this->username):
    echo "<tr><td>$type->nomeevento</td>";
    echo "<td>$type->numerobiglietti</td><td>";?>
        <?php if($type->metodo==='V'){echo 'Visa';}
              if($type->metodo==='M'){echo 'Mastercard';}
              if($type->metodo==='B'){echo 'Bonifico bancario';}
    echo "</td></tr>";
        
    
endif; endforeach;?>
    </table></div>
