<?php
echo '<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>';
$filename='conferma.js';
echo $this->jS($filename);
$filename='rowColor.js';
echo $this->jS($filename);
?>
<h3>Profilo acquisto di <?php echo "$this->nome $this->cognome" ?></h3>
<div class=tabella id=gestione><table class=elenco><th>Eventi</th><th>Biglietti acquistati</th><th>Metodo di pagamento</th><th>Totale speso</th>
<?php foreach ($this->acq as $type):
    if($type->username===$this->username):
    echo "<tr><td>$type->nomeevento</td>";
    echo "<td>$type->numerobiglietti</td><td>";?>
        <?php if($type->metodo==='V'){echo 'Visa';}
              if($type->metodo==='M'){echo 'Mastercard';}
              if($type->metodo==='B'){echo 'Bonifico bancario';}
              if($type->metodo==='P'){echo 'Paypal';}
    $tot=0;
    foreach ($this->pr as $t){
        if($t->nome===$type->nomeevento){
            if($type->sconto!=0){$sco=(($t->prezzo*$type->sconto)/100);$tot=(($t->prezzo-$sco)*$type->numerobiglietti);}
            else {$tot=($t->prezzo*$type->numerobiglietti);}}
        }
    echo "</td><td>$tot €</td></tr>";
        
    
endif; endforeach;?>
    </table></div>
